version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    restart: unless-stopped
    networks:
      - mood-journal-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - web
    networks:
      - mood-journal-network

networks:
  mood-journal-network:
    driver: bridge